# Example configuration file for the AIDC Facilitator application auth
# Change the password and rename the file to config.yaml
# It will be automatically hashed during the first run

credentials:
  usernames:
    admin:
      first_name: John
      last_name: Doe
      password: admin-pass
      roles:
      - admin
    attendee:
      password: attendee-pass
      roles:
      - user
