name: Azure Bicep Template Analysis

on:
  workflow_dispatch:
  workflow_call:
  pull_request:
    branches: 
      - main
      - dev
      - release/*
    paths:
      - "infra/**"
      - ".github/workflows/03-bicep-security.yml"
  push:
    branches:
      - main
      - dev
      - release/*
    paths:
      - "infra/**"
      - ".github/workflows/03-bicep-security.yml"

permissions:
  contents: read # Allows actions/checkout to fetch the code
  issues: read # only needed for private repository
  actions: read # needed to upload SARIF results to the security tab (https://github.com/github/codeql-action/issues/2117)
  checks: write
  pull-requests: write # only needed unless run with comment_mode: off

jobs:
  checkov-scan:
    runs-on: ubuntu-latest
    name: Checkov Bicep Analysis
    permissions:
      security-events: write # Allows github/codeql-action/upload-sarif to upload SARIF results
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run Checkov Action
        id: checkov
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: infra/
          config_file: infra/.checkov.yaml # Use project-specific configuration

      # need code scanning activated to upload SARIF results to security tab
      - name: Upload SARIF Results to GitHub
        if: (!cancelled())
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: bicep_results.sarif
          category: bicep-scan
      - name: Upload Test Results
        if: (!cancelled())
        uses: actions/upload-artifact@v4
        with:
          name: Bicep Test Results
          path: bicep_results.xml

  publish-infra-test-results:
    name: "Publish Infra Tests Results"
    needs: checkov-scan
    runs-on: ubuntu-latest
    if: (!cancelled())

    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v5
        with:
          path: artifacts

      - name: Publish Infra Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          files: "artifacts/**/*.xml"
