name: 04 Bandit Security Scan
on:
  workflow_dispatch:
  push:
    branches: ["dev", "main"]
    paths:
      - "src/**"
      - ".github/workflows/04-bandit-security.yml"
  pull_request:
    branches: ["dev", "main"]
  schedule:
    - cron: "41 3 * * 1"
permissions: {}

concurrency:
  group: bandit-${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build-and-test:
    name: Bandit Security Analysis
    runs-on: ubuntu-latest
    permissions:
      contents: read # to checkout code
      actions: read # to read workflow run status
      security-events: write # to upload SARIF results to security tab
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Install Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6
        with:
          python-version: 3.12

      - name: Install uv
        uses: astral-sh/setup-uv@1e862dfacbd1d6d858c55d9b792c756523627244 # v7.1.4
        with:
          enable-cache: false

      - name: bandit security scan (SARIF)
        if: always()
        run: uv run bandit -c .tools/.bandit.yml -r -f sarif -o results.sarif . || true

      - name: Upload SARIF file
        if: (!cancelled())
        uses: github/codeql-action/upload-sarif@e12f0178983d466f2f6028f5cc7a6d786fd97f4b # v4.31.4
        with:
          # Path to SARIF file relative to the root of the repository
          sarif_file: ${{github.workspace}}/results.sarif
          # Optional category for the results
          # Used to differentiate multiple results for one commit
          category: bandit-scan
