name: Format PR

on:
  issue_comment:
    types: [created]

jobs:
  format:
    if: github.event.issue.pull_request && contains(github.event.comment.body, '/format')
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: read

    steps:
      - name: Get PR REF
        id: ref
        uses: actions/github-script@v8
        with:
          result-encoding: string
          retries: 3
          script: |
            const { owner, repo, number } = context.issue;
            const pr = await github.rest.pulls.get({
              owner,
              repo,
              pull_number: number,
            });
            return pr.data.head.ref

      - uses: actions/checkout@v5
        with:
          token: ${{ secrets.PUSH_PAT }}
          repository: ${{ github.repository }}
          ref: ${{ steps.ref.outputs.result }}

      - name: Install Python
        uses: actions/setup-python@v6
        with:
          python-version: 3.12

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Fix formatting with pre-commit
        run: |
          # Install dependencies
          uv sync --only-group dev --directory src
          . src/.venv/bin/activate
          set +e # Don't exit immediately if pre-commit fails
          if uv run pre-commit run --all-files; then
              echo "Pre-commit checks passed or made changes."
          else
              set -e # If the next one still fails, just fail the job
              echo "Pre-commit checks failed. Running a second time to fix issues."
              uv run pre-commit run --all-files
          fi

      - name: Commit and push changes
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git add -A
          git diff --staged --quiet || git commit -m "Auto-format code with Black and Ruff"
          git push
