name: 99 Weekly dependabot checks
on:
  workflow_dispatch:
  schedule:
    - cron: "3 2 1 * *"

permissions:
  issues: write
  contents: read

jobs:
  evergreen:
    name: evergreen
    runs-on: ubuntu-latest

    steps:
      - name: Run evergreen action
        uses: github/evergreen@4469dee2f3c007933f1e8a2356ac15e03f7a832c # v1.24.8
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPOSITORY: ${{ github.repository }}
